In [1]:
import uproot
import numpy as np
import matplotlib.pyplot as plt

~~~cpp
rdf = ROOT::RDataFrame("Events", "/grid_mnt/data__data.polcms/cms/vernazza/cmt/Categorization/ul_2017_ZZ_v12/tt_sl/cat_ZZ_elliptical_cut_90_etau/prod_240327/data_25.root")
rdf.Filter("!((event == 178049355) && (bunchCrossing == 4294967295))").Snapshot("Events", "tt_sl_25_fixed.root")
~~~

~~~cpp
rdf = ROOT::RDataFrame("Events", "/grid_mnt/data__data.polcms/cms/cuisset/cmt/Categorization/ul_2017_ZbbHtt_v12/tt_sl/cat_ZbbHtt_elliptical_cut_90_etau/prod_240327/data_25.root")
rdf.Filter("!((event == 178049355) && (bunchCrossing == 4294967295))").Snapshot("Events", "/grid_mnt/data__data.polcms/cms/cuisset/cmt/Categorization/ul_2017_ZbbHtt_v12/tt_sl/cat_ZbbHtt_elliptical_cut_90_etau/prod_240327/data_25_fixed.root")
~~~
~~~cpp
rdf = ROOT::RDataFrame("Events", "/grid_mnt/data__data.polcms/cms/cuisset/cmt/Categorization/ul_2017_ZttHbb_v12/tt_sl/cat_ZttHbb_elliptical_cut_90_etau/prod_240327/data_25.root")
rdf.Filter("!((event == 178049355) && (bunchCrossing == 4294967295))").Snapshot("Events", "/grid_mnt/data__data.polcms/cms/cuisset/cmt/Categorization/ul_2017_ZttHbb_v12/tt_sl/cat_ZttHbb_elliptical_cut_90_etau/prod_240327/data_25_fixed.root")
~~~

~~~cpp
rdf = ROOT::RDataFrame("Events", "/grid_mnt/data__data.polcms/cms/vernazza/cmt/Categorization/ul_2017_ZZ_v12/tt_sl/cat_ZZ_elliptical_cut_90_CR_etau/prod_240318/data_25.root")
rdf.Filter("!((event == 178049355) && (bunchCrossing == 4294967295))").Snapshot("Events", "tt_sl_25_fixed_ZZ_CR.root")
~~~

~~~cpp
rdf = ROOT::RDataFrame("Events", "/grid_mnt/data__data.polcms/cms/cuisset/cmt/Categorization/ul_2017_ZbbHtt_v12/tt_sl/cat_ZbbHtt_elliptical_cut_90_CR_etau/prod_240318/data_25.root")
rdf.Filter("!((event == 178049355) && (bunchCrossing == 4294967295))").Snapshot("Events", "/grid_mnt/data__data.polcms/cms/cuisset/cmt/Categorization/ul_2017_ZbbHtt_v12/tt_sl/cat_ZbbHtt_elliptical_cut_90_CR_etau/prod_240318/data_25_fixed.root")
~~~
~~~cpp
rdf = ROOT::RDataFrame("Events", "/grid_mnt/data__data.polcms/cms/cuisset/cmt/Categorization/ul_2017_ZttHbb_v12/tt_sl/cat_ZttHbb_elliptical_cut_90_CR_etau/prod_240318/data_25.root")
rdf.Filter("!((event == 178049355) && (bunchCrossing == 4294967295))").Snapshot("Events", "/grid_mnt/data__data.polcms/cms/cuisset/cmt/Categorization/ul_2017_ZttHbb_v12/tt_sl/cat_ZttHbb_elliptical_cut_90_CR_etau/prod_240318/data_25_fixed.root")
~~~


~~~cpp
rdf = ROOT::RDataFrame("Events", "/grid_mnt/data__data.polcms/cms/vernazza/cmt/Categorization/ul_2017_ZZ_v12/tt_sl/cat_ZZ_elliptical_cut_90_sr/prod_240318/data_25.root")
rdf.Filter("!((event == 178049355) && (bunchCrossing == 4294967295))").Snapshot("Events", "tt_sl_25_fixed_ZZ_cat_sr.root")
~~~

~~~cpp
rdf = ROOT::RDataFrame("Events", "/grid_mnt/data__data.polcms/cms/cuisset/cmt/Categorization/ul_2017_ZbbHtt_v12/tt_sl/cat_ZbbHtt_elliptical_cut_90_sr/prod_240312/data_25.root")
rdf.Filter("!((event == 178049355) && (bunchCrossing == 4294967295))").Snapshot("Events", "/grid_mnt/data__data.polcms/cms/cuisset/cmt/Categorization/ul_2017_ZbbHtt_v12/tt_sl/cat_ZbbHtt_elliptical_cut_90_sr/prod_240312/data_25_fixed.root")
~~~
~~~cpp
rdf = ROOT::RDataFrame("Events", "/grid_mnt/data__data.polcms/cms/cuisset/cmt/Categorization/ul_2017_ZttHbb_v12/tt_sl/cat_ZttHbb_elliptical_cut_90_sr/prod_240312/data_25.root")
rdf.Filter("!((event == 178049355) && (bunchCrossing == 4294967295))").Snapshot("Events", "/grid_mnt/data__data.polcms/cms/cuisset/cmt/Categorization/ul_2017_ZttHbb_v12/tt_sl/cat_ZttHbb_elliptical_cut_90_sr/prod_240312/data_25_fixed.root")
~~~


~~~cpp
rdf = ROOT::RDataFrame("Events", "/grid_mnt/data__data.polcms/cms/vernazza/cmt/Categorization/ul_2017_ZZ_v12/tt_sl/cat_ZZ_elliptical_cut_90_sr/prod_240312/data_25.root")
rdf.Filter("!((event == 178049355) && (bunchCrossing == 4294967295))").Snapshot("Events", "tt_sl_25_fixed_ZZ_cat_sr_prod_240312.root")
~~~

~~~cpp
rdf = ROOT::RDataFrame("Events", "/grid_mnt/data__data.polcms/cms/cuisset/cmt/Categorization/ul_2017_ZbbHtt_v12/tt_sl/cat_ZbbHtt_elliptical_cut_90_sr/prod_240312_DNNinput/data_25.root")
rdf.Filter("!((event == 178049355) && (bunchCrossing == 4294967295))").Snapshot("Events", "/grid_mnt/data__data.polcms/cms/cuisset/cmt/Categorization/ul_2017_ZbbHtt_v12/tt_sl/cat_ZbbHtt_elliptical_cut_90_sr/prod_240312_DNNinput/data_25_fixed.root")
~~~
~~~cpp
rdf = ROOT::RDataFrame("Events", "/grid_mnt/data__data.polcms/cms/cuisset/cmt/Categorization/ul_2017_ZttHbb_v12/tt_sl/cat_ZttHbb_elliptical_cut_90_sr/prod_240312_DNNinput/data_25.root")
rdf.Filter("!((event == 178049355) && (bunchCrossing == 4294967295))").Snapshot("Events", "/grid_mnt/data__data.polcms/cms/cuisset/cmt/Categorization/ul_2017_ZttHbb_v12/tt_sl/cat_ZttHbb_elliptical_cut_90_sr/prod_240312_DNNinput/data_25_fixed.root")
~~~

## cat_base
~~~cpp
rdf = ROOT::RDataFrame("Events", "/grid_mnt/data__data.polcms/cms/vernazza/cmt/Categorization/ul_2017_ZZ_v12/tt_sl/cat_base/prod_240312/data_25.root")
rdf.Filter("!((event == 178049355) && (bunchCrossing == 4294967295))").Snapshot("Events", "tt_sl_25_fixed_cat_base.root")
~~~

~~~cpp
rdf = ROOT::RDataFrame("Events", "/grid_mnt/data__data.polcms/cms/cuisset/cmt/Categorization/ul_2017_ZbbHtt_v12/tt_sl/cat_base/prod_240312/data_25.root")
rdf.Filter("!((event == 178049355) && (bunchCrossing == 4294967295))").Snapshot("Events", "/grid_mnt/data__data.polcms/cms/cuisset/cmt/Categorization/ul_2017_ZbbHtt_v12/tt_sl/cat_base/prod_240312/data_25_fixed.root")
~~~
~~~cpp
rdf = ROOT::RDataFrame("Events", "/grid_mnt/data__data.polcms/cms/cuisset/cmt/Categorization/ul_2017_ZttHbb_v12/tt_sl/cat_base/prod_240312/data_25.root")
rdf.Filter("!((event == 178049355) && (bunchCrossing == 4294967295))").Snapshot("Events", "/grid_mnt/data__data.polcms/cms/cuisset/cmt/Categorization/ul_2017_ZttHbb_v12/tt_sl/cat_base/prod_240312/data_25_fixed.root")
~~~

## Preprocess
~~~cpp
rdf = ROOT::RDataFrame("Events", "/grid_mnt/data__data.polcms/cms/vernazza/cmt/PreprocessRDF/ul_2017_ZZ_v12/tt_sl/cat_base_selection/prod_240305/data_25.root")
rdf.Filter("!((event == 178049355) && (bunchCrossing == 4294967295))").Snapshot("Events", "tt_sl_25_preproc_ZZ.root")
~~~

~~~cpp
rdf = ROOT::RDataFrame("Events", "/grid_mnt/data__data.polcms/cms/vernazza/cmt/PreprocessRDF/ul_2018_ZbbHtt_v12/tt_sl/cat_base_selection/prod_240305/data_25.root")
rdf.Filter("!((event == 178049355) && (bunchCrossing == 4294967295))").Snapshot("Events", "tt_sl_25_preproc_ZbbHtt.root")
~~~
~~~cpp
rdf = ROOT::RDataFrame("Events", "/grid_mnt/data__data.polcms/cms/vernazza/cmt/PreprocessRDF/ul_2018_ZttHbb_v12/tt_sl/cat_base_selection/prod_240305/data_25.root")
rdf.Filter("!((event == 178049355) && (bunchCrossing == 4294967295))").Snapshot("Events", "tt_sl_25_preproc_ZttHbb.root")
~~~

In [2]:
# t = uproot.open("/scratch/cuisset/cmt/tt_sl_25_fixed.root:Events")
# t = uproot.open("/grid_mnt/data__data.polcms/cms/cuisset/cmt/Categorization/ul_2017_ZbbHtt_v12/tt_sl/cat_ZbbHtt_elliptical_cut_90_etau/prod_240327/data_25.root:Events")
t = uproot.open("/scratch/cuisset/cmt/MergeCategorization/ul_2017_ZbbHtt_v12/tt_sl/cat_base/prod_240318/data_0.root:Events")

In [3]:
weight = "genWeight*puWeight*DYstitchEasyWeight*prescaleWeight*trigSF*idAndIsoAndFakeSF*PUjetID_SF*bTagweightReshape"
col = t.arrays(weight, library="np")[weight]
np.any(np.isnan(col)), np.min(col), np.max(col)

(True, nan, nan)

In [4]:
np.argwhere(np.isnan(col))

array([[1945811]])

In [51]:
t.arrays(weight, entry_start=4047, entry_stop=4048)[0]

<Record {...} type='{"genWeight*puWeight*DYstitchEasyWeight*prescaleWeight*...'>

In [5]:
evt = t.arrays(entry_start=1945811, entry_stop=1945811+1)[0]
for key in evt.fields:
    if True or np.any(np.isnan(evt[key])):
        print(f"{key} = " + str(evt[key]))

bunchCrossing = 4294967295
event = 178049355
luminosityBlock = 178050
nElectron = 1
nFatJet = 1
nGenPart = 17
nJet = 9
nLHEPdfWeight = 103
nLHEReweightingWeight = 0
nLHEScaleWeight = 9
nMuon = 0
nPSWeight = 4
nTau = 1
nTauProd = 6
run = 1
Electron_eta = [-0.334]
Electron_mass = [-0.00311]
Electron_phi = [-0.492]
Electron_pt = [33]
FatJet_eta = [-1.5]
FatJet_mass = [68.6]
FatJet_phi = [1.29]
FatJet_pt = [253]
GenPart_eta = [2.28e+04, -2.36e+04, -1.58, -1.63, -1.58, ..., -0.334, -1.4, -1.17, -0.229]
GenPart_genPartIdxMother = [-1, -1, 0, 0, 2, 3, 4, 4, 6, 5, 5, 8, 8, 11, 12, 9, 9]
GenPart_mass = [0, 0, 174, 173, 173, 173, 82.2, 0, 82.2, 81, 0, 0, 0, 0, 0, 0, 0]
GenPart_pdgId = [21, 21, 6, -6, 6, -6, 24, 5, 24, -24, -5, -11, 12, -11, 12, 1, -2]
GenPart_phi = [0, 0, -1.98, 1.21, -1.96, 1.2, ..., -0.492, 2.83, -0.492, 2.83, 0.98, -1.46]
GenPart_pt = [0, 0, 148, 156, 142, 162, 9.66, 136, ..., 132, 32.5, 40, 32.5, 40, 56, 26.1]
GenPart_status = [21, 21, 22, 22, 62, 62, 22, 23, 52, 22, 23, 23,

In [55]:
evt[["event", "luminosityBlock"]]

<Record {event: 178049355, ...} type='{event: uint64, luminosityBlock: uint32}'>

In [7]:
dnn = t["dnn_ZZbbtt_kl_1"].array(library="np")
dnn

array([0.3629115 , 0.66855   , 0.80060226, ..., 0.01661257, 0.01006833,
       0.14624418], dtype=float32)

In [34]:
kinfit = t["ZZKinFit_mass"].array(library="np")
kinfit

array([183.79044248, 228.317454  , 271.114144  , ..., 485.27139371,
         0.        , 225.75350633])

In [22]:
dnns_cols = uproot.concatenate("/grid_mnt/data__data.polcms/cms/vernazza/cmt/Categorization/ul_2017_ZZ_v12/tt_sl/cat_ZZ_elliptical_cut_90_etau/prod_240327/data_*.root:Events",
filter_name="dnn_ZZbbtt_kl_1*", library="np")
dnns_cols

In [25]:
dnns_cols

{'dnn_ZZbbtt_kl_1': array([0.48550493, 0.01637449, 0.0240656 , ..., 0.20031454, 0.14812618,
        0.21200718], dtype=float32),
 'dnn_ZZbbtt_kl_1_corr_up': array([0.48550493, 0.01637449, 0.0240656 , ..., 0.20031454, 0.14812618,
        0.21200718], dtype=float32),
 'dnn_ZZbbtt_kl_1_corr_down': array([0.48550493, 0.01637449, 0.0240656 , ..., 0.20031454, 0.14812618,
        0.21200718], dtype=float32),
 'dnn_ZZbbtt_kl_1_smeared_up': array([0.45146304, 0.01395875, 0.0222287 , ..., 0.19597618, 0.14942162,
        0.17869757], dtype=float32),
 'dnn_ZZbbtt_kl_1_smeared_down': array([0.48583007, 0.018055  , 0.02381711, ..., 0.20442565, 0.14678474,
        0.22734824], dtype=float32),
 'dnn_ZZbbtt_kl_1_Total_up': array([0.4778319 , 0.01639314, 0.0240068 , ..., 0.20252718, 0.14932735,
        0.16539901], dtype=float32),
 'dnn_ZZbbtt_kl_1_Total_down': array([0.46937147, 0.01638768, 0.02179417, ..., 0.2075324 , 0.14706801,
        0.22818129], dtype=float32)}

In [27]:
for col in dnns_cols.values():
    print(np.any(np.isnan(col)), np.min(col), np.max(col))

False 8.790396e-08 0.9991063
False 8.790396e-08 0.9991063
False 8.790396e-08 0.9991063
False 8.3112944e-08 0.99911016
False 6.37301e-08 0.9991118
False 8.685362e-08 0.9991016
False 8.226754e-08 0.99910986


False

In [30]:
preplot = uproot.open("/grid_mnt/data__data.polcms/cms/vernazza/cmt/PrePlot/ul_2017_ZZ_v12/tt_sl/cat_ZZ_elliptical_cut_90_etau/prod_240327/data__etau_os_iso_25.root")
preplot["ZZKinFit_mass"]

<TH1D (version 3) at 0x7f32e5b803d0>

In [32]:
preplot["ZZKinFit_mass"].values()

array([    0.        ,  5272.72554037, 24326.4648298 , 32009.32818206,
       24065.49215037, 30582.0749073 , 22643.30913319, 17403.12204522,
       16823.42440191,  9282.74987454, 11490.36295236,  9308.22297735,
        4236.26666367,  4000.5675038 ,  3610.71428187,  4612.34862595,
        1985.3335982 ,  2412.52070416,  2138.33219282,  1166.45343466,
        1837.03484378,   985.76823252,   258.47261457,   565.04553791,
         395.43576113,   288.66852782,            nan,     0.        ,
           0.        ,     0.        ,   364.34076744,     0.        ,
           0.        ,     0.        ,     0.        ,     0.        ,
           0.        ,     0.        ,     0.        ,     0.        ,
           0.        ,   244.44786556,     0.        ,     0.        ,
           0.        ,     0.        ,     0.        ,     0.        ,
           0.        ,     0.        ])