In [10]:
import uproot
import numpy as np
import subprocess

In [8]:
eos_server = "root://eos.grif.fr"
eos_commands = ["eos", "-b", eos_server]
eos_basepath_crab = "/eos/grif/cms/llr/store/user/tcuisset/boostedTaus/2018_prod/"
eos_output_path = "/eos/grif/cms/llr/store/user/tcuisset/boostedTaus/2018_MC/"
def run_eos_cmd(*args):
    ret = subprocess.run([ *eos_commands, *args], stdout=subprocess.PIPE, check=True)
    return ret.stdout.decode().splitlines()
def list_files(dir, treeName="LuminosityBlocks"):
    return [f"root://eos.grif.fr//{dir}/{f}:{treeName}" for f in run_eos_cmd("ls", dir)]


In [22]:
x = uproot.concatenate(["root://eos.grif.fr///eos/grif/cms/llr/store/user/tcuisset/boostedTaus/2018_MC/st_top/NANO_NANO_99.root:LuminosityBlocks"], library="np")
x

{'run': array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=uint32),
 'luminosityBlock': array([ 2009,  2010,  3230, 22363, 38280, 38663,  2433,  2689,  3431,
         3432,  5411,  2143,  2576,  3023, 30043, 30044,  4612, 12545,
         3792, 51918, 52980,  2539,  2540, 26659,  2055,  3136,  4169,
         4170,  4357, 12391, 12739, 12740, 31243,  4449, 37037, 38047,
        48605,  2971, 52256, 52448,  2031,  2093,  2094,  2096,  2203,
         4834,  4841,  4842,  4996,  2032,  2071,  2072,  2095,  2129,
         2130,  4995, 51855, 54062,  4450, 37038, 38048, 38217, 38218,
         2432,  2529,  2530,  2592,  2999,  3000,  3581,  3582,  2866,
        14437, 12805, 27849, 36557,  2259, 30189, 15744,  4079, 13542,
        13662, 14461], dtype=uint32),


In [27]:
list_files("/eos/grif/cms/llr/store/user/tcuisset/boostedTaus/2018_MC/ST_t-channel_top_4f_InclusiveDecays")[0]

'root://eos.grif.fr///eos/grif/cms/llr/store/user/tcuisset/boostedTaus/2018_MC/ST_t-channel_top_4f_InclusiveDecays/NANO_NANO_1-1.root:LuminosityBlocks'

In [13]:
st_top = uproot.concatenate(list_files("/eos/grif/cms/llr/store/user/tcuisset/boostedTaus/2018_MC/st_top"), filter_name=["luminosityBlock"], library="np")["luminosityBlock"]

In [14]:
ST_t = uproot.concatenate(list_files("/eos/grif/cms/llr/store/user/tcuisset/boostedTaus/2018_MC/ST_t-channel_top_4f_InclusiveDecays"), filter_name=["luminosityBlock"], library="np")["luminosityBlock"]

In [16]:
np.intersect1d(st_top, ST_t)

array([  28,   29,   30, ..., 7998, 7999, 8000], dtype=uint32)

In [19]:
len(st_top), len(ST_t), len(np.intersect1d(st_top, ST_t))

(47573, 7650, 6205)

In [24]:
np.sort(st_top)

array([    28,     29,     30, ..., 199849, 199892, 199999], dtype=uint32)

In [25]:
np.sort(ST_t)

array([   1,    2,    3, ..., 7998, 7999, 8000], dtype=uint32)